version: "3.9"
services:
    api:
        build: ./usersapi
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04"
        ports:
            - "1433:1433"
        environment:
            - SA_PASSWORD=Password_22
            - ACCEPT_EULA=Y